data:
  size: -1
  dataset: PEGASUS

model:
  epochs: 30  
  
hp:
  architecture: MINIGAN
  batch_size: 5
  beta_1_d: 0.5
  beta_2_d: 0.9
  beta_1_g: 0.5
  beta_2_g: 0.9
  clip_value: 0.1
  d_extra_step: 3
  differential_privacy: true
  gp_weight: 20.0
  l2_norm_clip: 10.0
  lr_d: 0.05
  lr_g: 0.05
  n_critic: 5
  noise_multiplier: 0.6
  num_microbatches: 10

hputility:
  architecture: UNET
  learning_rate: 0.0001
  dropout_rate: 0.0
  batch_size: 64
